<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../unity_game/Assets/Afareet/Scripts/Vehicle/ArcadeDriveModifier.cs" Link="ArcadeDriveModifier.cs" />
  </ItemGroup>
</Project>
